export enum ConversationState {
  START = 'START',
  ASK_PRODUCT = 'ASK_PRODUCT',
  ASK_QUANTITY = 'ASK_QUANTITY',
  ASK_ADDRESS = 'ASK_ADDRESS',
  ASK_DELIVERY_TIME = 'ASK_DELIVERY_TIME',
  CONFIRM_ORDER = 'CONFIRM_ORDER',
  COMPLETED = 'COMPLETED',
}
